branch-defaults:
  eb_setup:
    environment: VOD-api
  master:
    environment: VOD-api
global:
  application_name: Virtual Open Days
  branch: null
  default_ec2_keyname: vod_key
  default_platform: PHP 7.3
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: vod
  repository: null
  sc: git
  workspace_type: Application

